export const formFields = [
  {
    index: 1,
    id: "name",
    name: "name",
    type: "text",
    required: true,
    label: "What's your name?",
    placeholder: "John Stephen",
    errorMessage: "Please enter a valid name",
  },
  {
    index: 2,
    id: "email",
    name: "email",
    type: "email",
    required: true,
    label: "What's your email?",
    placeholder: "john@stephen.com",
    errorMessage: "Please enter a valid email address",
  },
  {
    index: 3,
    id: "company",
    name: "company",
    type: "text",
    required: false,
    label: "What's the name of your organization?",
    placeholder: "John and Stephen ®",
    errorMessage: "Please enter an organization name",
  },
  {
    index: 4,
    id: "service",
    name: "service",
    type: "text",
    required: true,
    label: "What services are you looking for?",
    placeholder: "Web Design, Web Development ...",
    errorMessage: "Please enter a valid name",
  },
];
